[package]
name = "weights"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.frame-system]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'
