[package]
name = "sum-storage-rpc-runtime-api"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
sp-api = { version = '2.0.0-alpha.6', default_features = false}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
