[package]
name = "reservable-currency"
version = "2.0.0-alpha.6"
authors = ["4meta5"]
edition = "2018"
license = "GPL-3.0-or-later"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'balances/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'

[dependencies.frame-support]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.frame-system]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.balances]
default_features = false
package = 'pallet-balances'
version = '2.0.0-alpha.5'

[dev-dependencies.sp-core]
default_features = false
version = '2.0.0-alpha.6'

[dev-dependencies.sp-io]
default_features = false
version = '2.0.0-alpha.6'
