[package]
name = "simple-map"
version = "2.0.0-alpha.6"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
]

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }
frame-support = { default_features = false, version = '2.0.0-alpha.6' }
frame-system = { default_features = false, version = '2.0.0-alpha.6' }

[dev-dependencies]
sp-runtime = { default_features = false, version = '2.0.0-alpha.6' }
sp-core = { default_features = false, version = '2.0.0-alpha.6' }
sp-io = { default_features = false, version = '2.0.0-alpha.6' }
