sudo: false
dist: trusty
language: rust

before_install:
  - cargo install mdbook --vers '0.2.2' --debug --force

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 7905f70e76a2ed33e9df211b248905196d3d1408
  local-dir: book
  keep-history: false
  on:
    branch: master