[book]
authors = ["4meta5"]
multilingual = false
src = "src"
title = "Substrate Recipes"
description = "Substrate runtime design patterns"

[output.html]
additional-js = ["load.js", "config.js", "klaro.min.js"]