[package]
name = 'super-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.super-runtime]
package = 'super-runtime'
path = '../super-runtime'

[dependencies]
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/paritytech/substrate", branch = "master" }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/paritytech/substrate", branch = "master" }
