[package]
name = "sum-storage-rpc-runtime-api"
version = "2.0.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[dependencies]
sp-api = { rev = '3e651110aa06aa835790df63410a29676243fc54', git = 'https://github.com/paritytech/substrate.git', default_features = false}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
