[package]
name = "weight-fee-runtime"
version = "2.0.0-alpha.6"
authors = ["Anonymous"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
weights = { path = "../../pallets/weights", default-features = false }
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }

frame-executive = { version = '2.0.0-alpha.6', default-features = false }
frame-support = { version = '2.0.0-alpha.6', default-features = false }
frame-system = { version = '2.0.0-alpha.6', default-features = false }
sp-api = { version = '2.0.0-alpha.6', default-features = false }
sp-block-builder = { version = '2.0.0-alpha.6', default-features = false }
sp-consensus-babe = { version = '0.8.0-alpha.6', default-features = false }
sp-core = { version = '2.0.0-alpha.6', default-features = false }
sp-finality-grandpa = { version = '2.0.0-alpha.6', default-features = false }
sp-inherents = { version = '2.0.0-alpha.6', default-features = false }
sp-io = { version = '2.0.0-alpha.6', default-features = false }
sp-offchain = { version = '2.0.0-alpha.6', default-features = false }
sp-runtime = { version = '2.0.0-alpha.6', default-features = false }
sp-session = { version = '2.0.0-alpha.6', default-features = false }
sp-std = { version = '2.0.0-alpha.6', default-features = false }
sp-transaction-pool = { version = '2.0.0-alpha.6', default-features = false }
sp-version = { version = '2.0.0-alpha.6', default-features = false }

[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.6'

[dependencies.generic-asset]
default-features = false
package = 'pallet-generic-asset'
version = '2.0.0-alpha.6'

[dependencies.transaction-payment]
default-features = false
package = 'pallet-transaction-payment'
version = '2.0.0-alpha.6'

[dependencies.babe]
default-features = false
package = 'pallet-babe'
version = '2.0.0-alpha.6'

[dependencies.grandpa]
default-features = false
package = 'pallet-grandpa'
version = '2.0.0-alpha.6'

[dependencies.randomness-collective-flip]
default-features = false
package = 'pallet-randomness-collective-flip'
version = '2.0.0-alpha.6'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.6'

[dependencies.sudo]
default-features = false
package = 'pallet-sudo'
version = '2.0.0-alpha.6'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"babe/std",
	"balances/std",
	"sp-block-builder/std",
	"frame-executive/std",
	"generic-asset/std",
	"grandpa/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"sp-std/std",
	"sp-io/std",
	"serde",
	"sp-api/std",
	"sp-consensus-babe/std",
	"sp-finality-grandpa/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-session/std",
	"sudo/std",
	"frame-support/std",
	"frame-system/std",
	"timestamp/std",
	"transaction-payment/std",
	"sp-version/std",
	"weights/std",
	"sp-transaction-pool/std",
]
