[package]
name = "simple-crowdfund"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'balances/std',
    'sp-runtime/std',
    'rstd/std',
    'sp-core/std',
    'sp-storage/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
tag = 'v2.0.0-alpha.3'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
tag = 'v2.0.0-alpha.3'

[dependencies.sp-storage]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-alpha.3'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
tag = 'v2.0.0-alpha.3'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-alpha.3'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
tag = 'v2.0.0-alpha.3'

[dependencies.sp-core]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-alpha.3'
