[package]
name = "fixed-point"
version = "2.0.0-alpha.6"
authors = ["Joshy Orndorff"]
edition = "2018"
description = "A pallet that demonstrates using fixed point arithmetic on Substrate"
license = "GPL-3.0-or-later"
homepage = "https://github.com/substrate-developer-hub/recipes"
repository = "https://github.com/substrate-developer-hub/recipes"
documentation = "https://github.com/substrate-developer-hub/recipes"
#readme = ""

[package.metadata.substrate]
categories = [
	"fixed point",
	"tutorial",
	"recipe",
	"arithmetic",
]
# icon = "path/to/icon.png"
compatibility_version = "2.0.0-alpha.6"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
]

[dependencies.substrate-fixed]
git = 'https://github.com/encointer/substrate-fixed.git'
tag = "v0.5.4+sub_v0.1"

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'

[dependencies.frame-support]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.frame-system]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.sp-arithmetic]
default_features = false
version = '2.0.0-alpha.6'

[dev-dependencies.sp-core]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
default_features = false
version = '2.0.0-alpha.6'

[dependencies.sp-std]
default_features = false
version = '2.0.0-alpha.6'

[dev-dependencies.sp-io]
default_features = false
version = '2.0.0-alpha.6'
