[package]
name = "fixed-point"
version = "0.1.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
]

[dependencies.substrate-fixed]
git = 'https://github.com/encointer/substrate-fixed.git'
tag = "v0.5.4+sub_v0.1"

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.frame-support]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.frame-system]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.sp-arithmetic]
default_features = false

version = '2.0.0-alpha.5'

[dev-dependencies.sp-core]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.sp-std]
default_features = false

version = '2.0.0-alpha.5'

[dev-dependencies.sp-io]
default_features = false

version = '2.0.0-alpha.5'
