version: 2
jobs:
  check-modules:
    docker:
      - image: parity/rust:nightly
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Check Modules
          command: |
            cd kitchen/
            cargo check --all
      # - persist_to_workspace:
      #     # relative to working_directory
      #     root: "./"
      #     paths:
      #       - "./"
  
  #TODO Port the build from travis CI to here
  #build-book:



workflows:
  version: 2
  check-modules:
    jobs:
      - check-modules
      #     filters: *filter-non-gh-pages
      # - deploy:
      #     filters: *filter-only-master
      #     requires:
      #       - test
