[package]
name = "child-trie"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'system/std',
    'runtime-primitives/std',
]


[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.frame-support]
default_features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default_features = false

package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.runtime-primitives]
default_features = false

package = 'sp-runtime'
version = '2.0.0-alpha.5'

[dependencies.rstd]
default_features = false

package = 'sp-std'
version = '2.0.0-alpha.5'

[dependencies.primitives]
default_features = false

package = 'sp-core'
version = '2.0.0-alpha.5'
