[package]
name = 'api-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'api-runtime'
path = '../api-runtime'

[dependencies]
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", tag = 'v2.0.0-alpha.3' }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = 'v2.0.0-alpha.3' }
