[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
name = 'rpc-node'
version = '2.0.0-alpha.6'
homepage = 'https://substrate.dev/recipes'
repository = 'https://github.com/substrate-developer-hub/recipes'
description = 'A Substrate node that demonstrates a custom RPC endpoint'

[[bin]]
name = 'rpc-node'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'
structopt = "0.3.8"
runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sc-rpc = { version = '2.0.0-alpha.6' }
sc-client-api = '2.0.0-alpha.6'
sum-storage-rpc = { path = "../../pallets/sum-storage/rpc" }
ctrlc = { features = ['termination'], version = '3.1.3' }
futures01 = { package = 'futures', version = '0.1.29'}
sc-finality-grandpa = '0.8.0-alpha.6'
sp-finality-grandpa = '2.0.0-alpha.6'
sc-basic-authorship = '0.8.0-alpha.6'
sc-cli = '0.8.0-alpha.6'
sc-client = '0.8.0-alpha.6'
sc-consensus-aura = '0.8.0-alpha.6'
sc-executor = '0.8.0-alpha.6'
sc-network = '0.8.0-alpha.6'
sc-service = '0.8.0-alpha.6'
sc-transaction-pool = '2.0.0-alpha.6'
sp-consensus = '0.8.0-alpha.6'
sp-consensus-aura = '0.8.0-alpha.6'
sp-core = '2.0.0-alpha.6'
sp-inherents = '2.0.0-alpha.6'
sp-io = '2.0.0-alpha.6'
sp-runtime = '2.0.0-alpha.6'
sp-transaction-pool = '2.0.0-alpha.6'

[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = '2.0.0-alpha.6'
