[package]
name = "ringbuffer-queue"
version = "0.1.0"
authors = ["apopiak"]
edition = "2018"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
]

[dependencies]
codec = { package = 'parity-scale-codec', default-features = false, features = ['derive'], version = '1.3.0' }
frame-support = { default_features = false, version = '2.0.0-alpha.5' }
frame-system = { default_features = false, version = '2.0.0-alpha.5' }
sp-std = { default_features = false, version = '2.0.0-alpha.5' }

[dev-dependencies]
sp-runtime = { default_features = false, version = '2.0.0-alpha.5' }
sp-core = { default_features = false, version = '2.0.0-alpha.5' }
sp-io = { default_features = false, version = '2.0.0-alpha.5' }
