[package]
name = "simple-treasury"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'support/std',
    'system/std',
    'balances/std',
    'sp-runtime/std',
]

[dependencies]
serde = "1.0.102"

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.1.0'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-std'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dev-dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dev-dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '3e651110aa06aa835790df63410a29676243fc54'
