[package]
name = "super-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
simple-event = { package = "simple-event", path = "../../pallets/simple-event", default_features = false }
generic-event = { package = "generic-event", path = "../../pallets/generic-event", default_features = false }
adding-machine = { package = "adding-machine", path = "../../pallets/adding-machine", default-features = false }
single-value = { package = "single-value", path = "../../pallets/single-value", default-features = false }
vec-set = { package = "vec-set", path = "../../pallets/vec-set", default-features = false }
storage-cache = { package = "storage-cache", path = "../../pallets/storage-cache", default-features = false }
simple-map = { package = "simple-map", path = "../../pallets/simple-map", default-features = false }
double-map = { package = "double-map", path = "../../pallets/double-map", default-features = false }
linked-map = { package = "linked-map", path = "../../pallets/linked-map", default-features = false }
struct-storage = { package = "struct-storage", path = "../../pallets/struct-storage", default-features = false }
constant-config = { path = "../../pallets/constant-config", default-features = false }
basic-token = { package = "basic-token", path = "../../pallets/basic-token", default-features = false }
check-membership = { package = "check-membership", path = "../../pallets/check-membership", default-features = false }
execution-schedule = { package = "execution-schedule", path = "../../pallets/execution-schedule", default-features = false }
smpl-treasury = { package = "smpl-treasury", path = "../../pallets/smpl-treasury", default-features = false }
last-caller = { path = "../../pallets/last-caller", default-features = false }
default-instance = { path = "../../pallets/default-instance", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.runtime-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.balances]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.transaction-payment]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-transaction-payment'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.babe-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-consensus-babe'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.executive]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.indices]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.randomness-collective-flip]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.timestamp]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.sudo]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.sp-transaction-pool]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-offchain'
rev = '16817ab6b6b529ae32fc8151820c15dd1ed00291'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"babe/std",
	"babe-primitives/std",
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"grandpa/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"primitives/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-runtime/std",
  "sp-transaction-pool/std",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",

	# Recipes pallets
	"adding-machine/std",
	"basic-token/std",
	"check-membership/std",
	"constant-config/std",
	"double-map/std",
	"execution-schedule/std",
	"generic-event/std",
	"linked-map/std",
	"simple-event/std",
	"simple-map/std",
	"single-value/std",
	"storage-cache/std",
	"struct-storage/std",
	"vec-set/std",
]
