[package]
name = "lockable-currency"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'balances/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'

[dependencies.frame-support]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.frame-system]
default_features = false

version = '2.0.0-alpha.5'

[dependencies.balances]
default_features = false

package = 'pallet-balances'
version = '2.0.0-alpha.5'

[dev-dependencies.sp-core]
default_features = false

version = '2.0.0-alpha.5'

[dev-dependencies.sp-io]
default_features = false

version = '2.0.0-alpha.5'
