[package]
name = "randomness"
version = "2.0.0-alpha.6"
authors = ["4meta5"]
edition = "2018"

[dependencies]
# external dependencies
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }

# Substrate pallet/frame dependencies
frame-support = { version = '2.0.0-alpha.6', default_features = false }
frame-system = { version = '2.0.0-alpha.6', default_features = false }
sp-runtime = { version = '2.0.0-alpha.6', default_features = false }
sp-std = { version = '2.0.0-alpha.6', default_features = false }
sp-core = { version = '2.0.0-alpha.6', default_features = false }

[dev-dependencies]
sp-io = { version = '2.0.0-alpha.6' }
pallet-randomness-collective-flip = { version = '2.0.0-alpha.6' }
pallet-babe = { version = '2.0.0-alpha.6' }
pallet-timestamp = { version = '2.0.0-alpha.6' }

[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-runtime/std',
	'sp-core/std',
]
