[package]
name = "storage-cache"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[dependencies]
# external dependencies
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.1.0' }

# Substrate pallet/frame dependencies
support = { package = 'frame-support', version = '2.0.0-alpha.5', default_features = false }
system = { package = 'frame-system', version = '2.0.0-alpha.5', default_features = false }
sp-runtime = { version = '2.0.0-alpha.5', default_features = false }
sp-std = { version = '2.0.0-alpha.5', default_features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-alpha.5', default_features = false }
sp-io = { version = '2.0.0-alpha.5', default_features = false }

[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'support/std',
	'system/std',
	'sp-runtime/std',
]
