[package]
name = "storage-cache"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[dependencies]
# external dependencies
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.1.0' }

# Substrate pallet/frame dependencies
support = { package = 'frame-support', git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }
system = { package = 'frame-system', git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }
sp-std = { git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }

[dev-dependencies]
sp-core = { git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', tag = 'v2.0.0-alpha.3', default_features = false }

[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'support/std',
	'system/std',
	'sp-runtime/std',
]
