[package]
name = "single-value"
version = "2.0.0-alpha.6"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
]

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }
frame-support = { version = '2.0.0-alpha.6',  default_features = false }
frame-system  = { version = '2.0.0-alpha.6',  default_features = false }
sp-runtime = { version = '2.0.0-alpha.6',  default_features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-alpha.6', default_features = false }
sp-io = { version = '2.0.0-alpha.6', default_features = false }
