name: Build and Deploy Book

on:
  push:
    branches:
    - master

jobs:
  build-deploy-book:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'
        # mdbook-version: 'latest'

    - name: Install mdbook-linkcheck
      run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            bash -s -- --git Michael-F-Bryan/mdbook-linkcheck

    - name: Build Book
      run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./book/html
