name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2019-11-15
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - uses: actions/checkout@v2
    - name: Check Kitchen
      run: cd kitchen/modules && cargo check --all
    - name: Test Kitchen
      run: cd kitchen/modules && cargo test --all
