name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Enter Kitchen Modules
      run: cd kitchen/modules
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2019-11-15
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Compile Modules
      run: cargo check --all
    - name: Run Tests
      run: cargo test --all
